'use client'
import * as React from 'react'
import { MessageCircle, Send } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { useAuth } from '@/components/auth/auth-provider'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card,CardContent } from '@/components/ui/card'

export default function MessagesPage(){
 const supabase=React.useMemo(()=>createClient(),[]);const {user,loading}=useAuth();const [conversations,setConversations]=React.useState<any[]>([]);const [selected,setSelected]=React.useState<string>('');const [messages,setMessages]=React.useState<any[]>([]);const [text,setText]=React.useState('')
 const loadConversations=React.useCallback(async()=>{if(!user)return;const {data}=await supabase.from('conversations').select('id,booking_id,client_id,provider_id,created_at,booking:bookings(code,event_name,event_date),provider:service_providers(business_name)').order('created_at',{ascending:false});setConversations(data||[]);if(!selected&&data?.[0])setSelected(data[0].id)},[supabase,user,selected])
 const loadMessages=React.useCallback(async()=>{if(!selected)return;const {data}=await supabase.from('messages').select('*').eq('conversation_id',selected).order('created_at');setMessages(data||[])},[supabase,selected])
 React.useEffect(()=>{loadConversations()},[loadConversations]);React.useEffect(()=>{loadMessages();if(!selected)return;const ch=supabase.channel(`conversation-${selected}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${selected}`},()=>loadMessages()).subscribe();return()=>{supabase.removeChannel(ch)}},[selected,loadMessages,supabase])
 async function send(){if(!text.trim()||!selected||!user)return;const body=text.trim();setText('');await supabase.from('messages').insert({conversation_id:selected,sender_id:user.id,body});await loadMessages()}
 if(!loading&&!user)return <div className="mx-auto max-w-4xl px-4 py-20 text-center"><MessageCircle className="mx-auto size-8 text-primary"/><h1 className="mt-4 text-2xl font-bold">Inicia sesión para ver tus mensajes</h1></div>
 return <div className="mx-auto max-w-6xl px-4 py-10"><p className="text-sm font-semibold text-primary">Comunicación</p><h1 className="mt-1 text-3xl font-extrabold">Mensajes</h1><div className="mt-8 grid min-h-[560px] overflow-hidden rounded-2xl border bg-card md:grid-cols-[320px_1fr]"><aside className="border-b md:border-b-0 md:border-r"><div className="border-b p-4 font-semibold">Conversaciones</div><div className="max-h-[500px] overflow-y-auto">{conversations.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`w-full border-b p-4 text-left hover:bg-muted ${selected===c.id?'bg-muted':''}`}><b className="text-sm">{c.provider?.business_name||'Prestador'}</b><p className="mt-1 text-xs text-muted-foreground">{c.booking?.event_name||'Evento'} · {c.booking?.code}</p></button>)}{conversations.length===0&&<p className="p-6 text-sm text-muted-foreground">Aún no tienes conversaciones.</p>}</div></aside><section className="flex min-h-[520px] flex-col"><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map(m=><div key={m.id} className={`flex ${m.sender_id===user?.id?'justify-end':'justify-start'}`}><div className={`max-w-[80%] rounded-2xl px-4 py-2 text-sm ${m.sender_id===user?.id?'bg-primary text-primary-foreground':'bg-muted'}`}><p>{m.body}</p><p className="mt-1 text-[10px] opacity-70">{new Date(m.created_at).toLocaleString('es-CL')}</p></div></div>)}</div>{selected&&<div className="flex gap-2 border-t p-4"><Input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Escribe un mensaje..."/><Button onClick={send} disabled={!text.trim()}><Send/></Button></div>}</section></div></div>
}
