'use client'
import * as React from 'react'
import Link from 'next/link'
import { Bell } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { useAuth } from '@/components/auth/auth-provider'
import { Button } from '@/components/ui/button'

export function NotificationsMenu(){const {user}=useAuth();const supabase=React.useMemo(()=>createClient(),[]);const [rows,setRows]=React.useState<any[]>([]);const [open,setOpen]=React.useState(false);const load=React.useCallback(async()=>{if(!user)return setRows([]);const {data}=await supabase.from('notifications').select('*').eq('user_id',user.id).is('read_at',null).order('created_at',{ascending:false}).limit(8);setRows(data||[])},[supabase,user]);React.useEffect(()=>{load();if(!user)return;const ch=supabase.channel(`notifications-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[load,supabase,user]);if(!user)return null;async function mark(id:string){await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);await load();setOpen(false)}return <div className="relative"><Button size="icon" variant="ghost" onClick={()=>setOpen(v=>!v)} aria-label="Notificaciones" className="relative"><Bell/>{rows.length>0&&<span className="absolute right-0 top-0 flex min-w-4 items-center justify-center rounded-full bg-destructive px-1 text-[9px] text-white">{rows.length}</span>}</Button>{open&&<div className="absolute right-0 top-11 z-50 w-80 overflow-hidden rounded-xl border bg-popover shadow-xl"><div className="border-b p-3 text-sm font-semibold">Notificaciones</div>{rows.length===0?<p className="p-5 text-sm text-muted-foreground">Sin notificaciones nuevas.</p>:rows.map(n=><Link key={n.id} href={n.href||'/cuenta'} onClick={()=>mark(n.id)} className="block border-b p-3 hover:bg-muted"><b className="text-sm">{n.title}</b><p className="mt-1 text-xs text-muted-foreground">{n.body}</p></Link>)}</div>}</div>}
