'use client'
import * as React from 'react'
import { CalendarDays, Plus, Trash2 } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'

export default function AvailabilityPage(){const supabase=React.useMemo(()=>createClient(),[]);const [providerId,setProviderId]=React.useState('');const [rows,setRows]=React.useState<any[]>([]);const [f,setF]=React.useState({date:'',start:'10:00',end:'23:00'});const load=React.useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('service_providers').select('id').eq('owner_id',user.id).maybeSingle();if(!p)return;setProviderId(p.id);const {data}=await supabase.from('provider_availability').select('*').eq('provider_id',p.id).gte('date',new Date().toISOString().slice(0,10)).order('date');setRows(data||[])},[supabase]);React.useEffect(()=>{load()},[load]);async function add(e:React.FormEvent){e.preventDefault();if(!providerId||!f.date)return;await supabase.from('provider_availability').insert({provider_id:providerId,date:f.date,start_time:f.start,end_time:f.end,available:true});setF({...f,date:''});await load()}async function remove(id:string){await supabase.from('provider_availability').delete().eq('id',id);await load()}return <div className="mx-auto max-w-5xl px-4 py-10"><p className="text-sm font-semibold text-primary">Prestador</p><h1 className="mt-1 text-3xl font-extrabold">Disponibilidad</h1><p className="mt-2 text-muted-foreground">Define fechas y horarios que los clientes podrán considerar al reservar.</p><div className="mt-8 grid gap-6 lg:grid-cols-[340px_1fr]"><Card><CardHeader><CardTitle className="flex gap-2"><CalendarDays/>Agregar disponibilidad</CardTitle></CardHeader><CardContent><form onSubmit={add} className="space-y-4"><label className="grid gap-1.5 text-sm">Fecha<Input type="date" required value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-1.5 text-sm">Desde<Input type="time" value={f.start} onChange={e=>setF({...f,start:e.target.value})}/></label><label className="grid gap-1.5 text-sm">Hasta<Input type="time" value={f.end} onChange={e=>setF({...f,end:e.target.value})}/></label></div><Button className="w-full"><Plus/>Agregar</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Próximas fechas</CardTitle></CardHeader><CardContent className="space-y-3">{rows.map(r=><div key={r.id} className="flex items-center justify-between rounded-xl border p-4"><div><b>{new Date(r.date+'T12:00:00').toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long'})}</b><p className="mt-1 text-sm text-muted-foreground">{String(r.start_time||'').slice(0,5)} – {String(r.end_time||'').slice(0,5)}</p></div><Button size="icon" variant="destructive" onClick={()=>remove(r.id)}><Trash2/></Button></div>)}{rows.length===0&&<p className="py-10 text-center text-sm text-muted-foreground">No has definido fechas todavía.</p>}</CardContent></Card></div></div>}
