import type { CategorySlug, Provider } from "./types"

const WEEKDAYS = [1, 2, 3, 4, 5]
const WEEKEND = [5, 6, 0]
const ALLDAYS = [0, 1, 2, 3, 4, 5, 6]

export const PROVIDERS: Provider[] = [
  // PARRILLEROS
  {
    id: "brasa-maestra",
    name: "Brasa Maestra",
    category: "parrilleros",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    rating: 4.9,
    reviews: 214,
    priceFrom: 70000,
    verified: true,
    featured: true,
    image: "/images/cat-parrilleros.png",
    gallery: ["/images/cat-parrilleros.png", "/images/cat-catering.png", "/images/hero-event.png"],
    tagline: "Parrilla premium con show en vivo",
    bio: "Somos un equipo de parrilleros con más de una década asando para eventos en toda la Región Metropolitana. Trabajamos cortes seleccionados y punto a pedido.",
    experienceYears: 12,
    eventsDone: 640,
    coverage: ["Puente Alto", "La Florida", "Santiago Centro", "Ñuñoa"],
    availableDays: WEEKEND,
    services: [
      { id: "p1", name: "Solo parrillero", description: "Llegamos, asamos y servimos. Tú pones las carnes.", price: 70000, unit: "por evento", popular: true },
      { id: "p2", name: "Parrillero + compras", description: "Nos encargamos de comprar los cortes y asarlos.", price: 180000, unit: "por evento" },
      { id: "p3", name: "Servicio completo", description: "Parrillero, carnes, acompañamientos y montaje.", price: 320000, unit: "por evento" },
    ],
    reviewList: [
      { author: "Camila R.", rating: 5, date: "Ago 2026", comment: "El asado quedó espectacular, todos preguntaron por ellos." },
      { author: "Diego M.", rating: 5, date: "Jul 2026", comment: "Puntuales y muy profesionales. El punto de la carne perfecto." },
    ],
  },
  {
    id: "fuego-lento",
    name: "Fuego Lento",
    category: "parrilleros",
    comuna: "Maipú",
    region: "Región Metropolitana",
    rating: 4.7,
    reviews: 128,
    priceFrom: 65000,
    verified: true,
    image: "/images/cat-parrilleros.png",
    gallery: ["/images/cat-parrilleros.png", "/images/cat-catering.png"],
    tagline: "Especialistas en cocción lenta y ahumados",
    bio: "Ahumados, costillar y cortes de cocción lenta. Ideal para eventos que buscan algo distinto.",
    experienceYears: 7,
    eventsDone: 310,
    coverage: ["Maipú", "Estación Central", "Santiago Centro"],
    availableDays: WEEKEND,
    services: [
      { id: "p1", name: "Solo parrillero", description: "Asamos tus cortes con técnica de fuego lento.", price: 65000, unit: "por evento" },
      { id: "p2", name: "Parrillero + compras", description: "Compramos y preparamos costillar y cortes premium.", price: 165000, unit: "por evento", popular: true },
    ],
    reviewList: [
      { author: "Fernanda S.", rating: 5, date: "Jun 2026", comment: "El costillar se deshacía. Increíble." },
    ],
  },
  // BARTENDERS
  {
    id: "coctel-santiago",
    name: "Cóctel Santiago",
    category: "bartenders",
    comuna: "Providencia",
    region: "Región Metropolitana",
    rating: 4.8,
    reviews: 176,
    priceFrom: 65000,
    verified: true,
    featured: true,
    image: "/images/cat-bartenders.png",
    gallery: ["/images/cat-bartenders.png", "/images/hero-event.png"],
    tagline: "Coctelería de autor para tus invitados",
    bio: "Bartenders profesionales con carta de autor. Montamos barra completa con cristalería e insumos.",
    experienceYears: 9,
    eventsDone: 420,
    coverage: ["Providencia", "Las Condes", "Ñuñoa", "Vitacura"],
    availableDays: ALLDAYS,
    services: [
      { id: "b1", name: "Solo bartender", description: "Bartender profesional, tú pones los insumos.", price: 65000, unit: "por evento" },
      { id: "b2", name: "Bartender + barra", description: "Barra montada, cristalería y bartender.", price: 140000, unit: "por evento", popular: true },
      { id: "b3", name: "Coctelería completa", description: "Barra, bartender, insumos y carta de autor.", price: 260000, unit: "por evento" },
    ],
    reviewList: [
      { author: "Josefa L.", rating: 5, date: "Ago 2026", comment: "Los tragos de autor fueron el hit de la noche." },
      { author: "Matías P.", rating: 4, date: "Jul 2026", comment: "Muy buenos, la barra quedó preciosa." },
    ],
  },
  {
    id: "barra-nomade",
    name: "Barra Nómade",
    category: "bartenders",
    comuna: "Ñuñoa",
    region: "Región Metropolitana",
    rating: 4.6,
    reviews: 94,
    priceFrom: 60000,
    verified: false,
    image: "/images/cat-bartenders.png",
    gallery: ["/images/cat-bartenders.png"],
    tagline: "Barra móvil para cualquier ocasión",
    bio: "Barra móvil de madera con estilo. Perfecta para matrimonios y cumpleaños.",
    experienceYears: 5,
    eventsDone: 180,
    coverage: ["Ñuñoa", "Providencia", "Macul", "Peñalolén"],
    availableDays: WEEKEND,
    services: [
      { id: "b1", name: "Solo bartender", description: "Atención de barra con tus insumos.", price: 60000, unit: "por evento" },
      { id: "b2", name: "Bartender + barra móvil", description: "Barra de madera montada más bartender.", price: 130000, unit: "por evento", popular: true },
    ],
    reviewList: [
      { author: "Ignacio T.", rating: 5, date: "May 2026", comment: "La barra móvil se veía increíble." },
    ],
  },
  // GARZONES
  {
    id: "servicio-elegante",
    name: "Servicio Elegante",
    category: "garzones",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    rating: 4.7,
    reviews: 141,
    priceFrom: 40000,
    verified: true,
    image: "/images/cat-garzones.png",
    gallery: ["/images/cat-garzones.png", "/images/hero-event.png"],
    tagline: "Garzones profesionales uniformados",
    bio: "Equipo de garzones con experiencia en eventos protocolares y sociales. Uniformados y capacitados.",
    experienceYears: 8,
    eventsDone: 520,
    coverage: ["Las Condes", "Vitacura", "Providencia", "La Reina"],
    availableDays: ALLDAYS,
    services: [
      { id: "g1", name: "1 garzón", description: "Un garzón por 5 horas de servicio.", price: 40000, unit: "por evento" },
      { id: "g2", name: "2 garzones", description: "Dos garzones para eventos medianos.", price: 80000, unit: "por evento", popular: true },
      { id: "g3", name: "Equipo de 4 garzones", description: "Servicio completo para eventos grandes.", price: 150000, unit: "por evento" },
    ],
    reviewList: [
      { author: "Andrea V.", rating: 5, date: "Ago 2026", comment: "Impecables, muy atentos con los invitados." },
    ],
  },
  // CATERING
  {
    id: "sabores-del-valle",
    name: "Sabores del Valle",
    category: "catering",
    comuna: "Providencia",
    region: "Región Metropolitana",
    rating: 4.8,
    reviews: 203,
    priceFrom: 90000,
    verified: true,
    featured: true,
    image: "/images/cat-catering.png",
    gallery: ["/images/cat-catering.png", "/images/cat-pasteleria.png"],
    tagline: "Banquetería y picoteos gourmet",
    bio: "Catering para todo tipo de eventos: tablas de picoteo, banquetería y menús personalizados.",
    experienceYears: 11,
    eventsDone: 610,
    coverage: ["Providencia", "Las Condes", "Ñuñoa", "Santiago Centro"],
    availableDays: ALLDAYS,
    services: [
      { id: "c1", name: "Tabla de picoteo", description: "Tabla premium para compartir (10-15 personas).", price: 90000, unit: "por tabla", popular: true },
      { id: "c2", name: "Picoteo por persona", description: "Variedad de bocados individuales.", price: 6500, unit: "por persona" },
      { id: "c3", name: "Banquetería completa", description: "Menú de entrada, fondo y postre.", price: 14000, unit: "por persona" },
    ],
    reviewList: [
      { author: "Paula G.", rating: 5, date: "Jul 2026", comment: "La comida estuvo deliciosa y bien presentada." },
    ],
  },
  // PASTELERIA
  {
    id: "dulce-obsesion",
    name: "Dulce Obsesión",
    category: "pasteleria",
    comuna: "Ñuñoa",
    region: "Región Metropolitana",
    rating: 4.9,
    reviews: 167,
    priceFrom: 35000,
    verified: true,
    image: "/images/cat-pasteleria.png",
    gallery: ["/images/cat-pasteleria.png"],
    tagline: "Tortas personalizadas y mesas dulces",
    bio: "Pastelería artesanal. Tortas temáticas, cupcakes y mesas dulces para toda celebración.",
    experienceYears: 6,
    eventsDone: 380,
    coverage: ["Ñuñoa", "Providencia", "Macul", "La Florida"],
    availableDays: ALLDAYS,
    services: [
      { id: "d1", name: "Torta personalizada", description: "Torta temática para 20-25 porciones.", price: 45000, unit: "por torta", popular: true },
      { id: "d2", name: "Mesa dulce", description: "Cupcakes, brownies, galletas y más.", price: 85000, unit: "por evento" },
    ],
    reviewList: [
      { author: "Valentina C.", rating: 5, date: "Ago 2026", comment: "La torta era hermosa y riquísima." },
    ],
  },
  // DJ
  {
    id: "beat-eventos",
    name: "Beat Eventos",
    category: "dj",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    rating: 4.7,
    reviews: 152,
    priceFrom: 120000,
    verified: true,
    featured: true,
    image: "/images/cat-dj.png",
    gallery: ["/images/cat-dj.png", "/images/hero-event.png"],
    tagline: "DJ con equipo e iluminación profesional",
    bio: "DJ para fiestas, matrimonios y corporativos. Equipo de sonido e iluminación incluidos.",
    experienceYears: 10,
    eventsDone: 480,
    coverage: ["Santiago Centro", "Providencia", "Las Condes", "Maipú"],
    availableDays: WEEKEND,
    services: [
      { id: "j1", name: "DJ básico", description: "DJ con equipo de sonido para hasta 50 personas.", price: 120000, unit: "por evento" },
      { id: "j2", name: "DJ + iluminación", description: "Sonido, luces y máquina de humo.", price: 190000, unit: "por evento", popular: true },
    ],
    reviewList: [
      { author: "Rodrigo A.", rating: 5, date: "Jul 2026", comment: "Leyó perfecto a la audiencia, todos bailaron." },
    ],
  },
  // DECORACION
  {
    id: "globos-y-magia",
    name: "Globos & Magia",
    category: "decoracion",
    comuna: "La Florida",
    region: "Región Metropolitana",
    rating: 4.6,
    reviews: 118,
    priceFrom: 55000,
    verified: false,
    image: "/images/cat-decoracion.png",
    gallery: ["/images/cat-decoracion.png"],
    tagline: "Arcos de globos y ambientación temática",
    bio: "Decoración con globos, arcos, centros de mesa y ambientación temática personalizada.",
    experienceYears: 4,
    eventsDone: 240,
    coverage: ["La Florida", "Puente Alto", "Macul", "Peñalolén"],
    availableDays: ALLDAYS,
    services: [
      { id: "de1", name: "Arco de globos", description: "Arco temático con tus colores.", price: 55000, unit: "por evento", popular: true },
      { id: "de2", name: "Ambientación completa", description: "Arco, centros de mesa y detalles.", price: 130000, unit: "por evento" },
    ],
    reviewList: [
      { author: "Karla D.", rating: 5, date: "Jun 2026", comment: "La decoración superó nuestras expectativas." },
    ],
  },
  // FOTOGRAFIA
  {
    id: "instante-foto",
    name: "Instante Foto",
    category: "fotografia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    rating: 4.9,
    reviews: 189,
    priceFrom: 100000,
    verified: true,
    image: "/images/cat-fotografia.png",
    gallery: ["/images/cat-fotografia.png", "/images/hero-event.png"],
    tagline: "Fotografía y video para tu evento",
    bio: "Cobertura fotográfica y de video profesional. Entrega de material editado en tiempo récord.",
    experienceYears: 9,
    eventsDone: 350,
    coverage: ["Providencia", "Las Condes", "Ñuñoa", "Vitacura"],
    availableDays: ALLDAYS,
    services: [
      { id: "f1", name: "Cobertura foto (3h)", description: "Fotógrafo por 3 horas + galería digital.", price: 100000, unit: "por evento", popular: true },
      { id: "f2", name: "Foto + video", description: "Cobertura completa foto y video editado.", price: 220000, unit: "por evento" },
    ],
    reviewList: [
      { author: "Sofía N.", rating: 5, date: "Ago 2026", comment: "Las fotos quedaron de revista." },
    ],
  },
  // MOBILIARIO
  {
    id: "arriendos-vega",
    name: "Arriendos Vega",
    category: "mobiliario",
    comuna: "Maipú",
    region: "Región Metropolitana",
    rating: 4.5,
    reviews: 87,
    priceFrom: 45000,
    verified: true,
    image: "/images/cat-mobiliario.png",
    gallery: ["/images/cat-mobiliario.png"],
    tagline: "Arriendo de mobiliario y equipamiento",
    bio: "Mesas, sillas, toldos, vajilla y mantelería. Despacho e instalación incluida.",
    experienceYears: 13,
    eventsDone: 720,
    coverage: ["Maipú", "Estación Central", "Santiago Centro", "La Florida"],
    availableDays: ALLDAYS,
    services: [
      { id: "m1", name: "Set mesa + sillas (10p)", description: "Mesa con 10 sillas y mantel.", price: 45000, unit: "por set", popular: true },
      { id: "m2", name: "Toldo 3x6", description: "Toldo con instalación incluida.", price: 90000, unit: "por evento" },
    ],
    reviewList: [
      { author: "Héctor M.", rating: 4, date: "May 2026", comment: "Todo llegó a tiempo y en buen estado." },
    ],
  },
]

export function getProvider(id: string): Provider | undefined {
  return PROVIDERS.find((p) => p.id === id)
}

export function getProvidersByCategory(category: CategorySlug): Provider[] {
  return PROVIDERS.filter((p) => p.category === category)
}
