import Link from 'next/link'
import { CalendarClock, DollarSign, PackageCheck, Plus, Star, Users } from 'lucide-react'
import { redirect } from 'next/navigation'
import { requireRole } from '@/lib/auth'
import { createClient } from '@/lib/supabase/server'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { formatCLP } from '@/lib/format'
import { ProviderBookingActions } from '@/components/provider-booking-actions'

export default async function ProviderDashboard(){
 const {profile}=await requireRole(['prestador','administrador']);const supabase=await createClient();const {data:provider}=await supabase.from('service_providers').select('*').eq('owner_id',profile.id).maybeSingle();if(!provider&&profile.role==='prestador')redirect('/prestador/onboarding')
 const providerId=provider?.id;const [{data:services},{data:items}]=await Promise.all([providerId?supabase.from('provider_services').select('*').eq('provider_id',providerId).order('created_at',{ascending:false}):Promise.resolve({data:[] as any[]}),providerId?supabase.from('booking_items').select('*,booking:bookings(code,event_name,event_date,event_time,address,guests,total,status,contact_name,contact_phone)').eq('provider_id',providerId).order('created_at',{ascending:false}).limit(12):Promise.resolve({data:[] as any[]})]);const pending=(items||[]).filter((x:any)=>['pendiente','esperando_confirmacion'].includes(x.provider_status)).length;const confirmed=(items||[]).filter((x:any)=>['confirmada','en_preparacion','en_curso'].includes(x.provider_status)).length;const revenue=(items||[]).filter((x:any)=>x.provider_status==='completada').reduce((s:number,x:any)=>s+(x.line_total||0),0)
 return <div className="mx-auto max-w-6xl px-4 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Prestador</p><h1 className="mt-1 text-3xl font-extrabold">{provider?.business_name||'Panel de prestador'}</h1><p className="mt-2 text-muted-foreground">Administra solicitudes, servicios y disponibilidad.</p></div><Button nativeButton={false} render={<Link href="/prestador/servicios"/>}><Plus/>Nuevo servicio</Button></div><div className="mt-8 grid grid-cols-2 gap-4 lg:grid-cols-5"><Kpi icon={CalendarClock} label="Solicitudes" value={String(pending)}/><Kpi icon={PackageCheck} label="Confirmadas" value={String(confirmed)}/><Kpi icon={Users} label="Servicios activos" value={String((services||[]).filter((s:any)=>s.active).length)}/><Kpi icon={Star} label="Rating" value={Number(provider?.rating||0).toFixed(1)}/><Kpi icon={DollarSign} label="Ingresos completados" value={formatCLP(revenue)}/></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_340px]"><Card><CardHeader><CardTitle>Solicitudes recientes</CardTitle></CardHeader><CardContent className="space-y-3">{(items||[]).length===0?<p className="py-10 text-center text-sm text-muted-foreground">Aún no recibes solicitudes.</p>:(items||[]).map((item:any)=><div key={item.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.booking?.event_name}</b><p className="mt-1 text-xs text-muted-foreground">{item.booking?.code} · {item.booking?.event_date} {item.booking?.event_time?.slice(0,5)} · {item.booking?.guests} personas</p><p className="mt-2 text-sm">{item.service_name}</p><ProviderBookingActions itemId={item.id} status={item.provider_status}/></div><div className="text-right"><b>{formatCLP(item.line_total)}</b><p className="mt-1 text-xs capitalize text-muted-foreground">{item.provider_status.replaceAll('_',' ')}</p></div></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Mis servicios</CardTitle></CardHeader><CardContent className="space-y-3">{(services||[]).slice(0,5).map((s:any)=><div key={s.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><b className="text-sm">{s.name}</b><span className="text-xs text-muted-foreground">{s.active?'Activo':'Pausado'}</span></div><p className="mt-1 text-sm font-semibold text-primary">{formatCLP(s.price)} <span className="font-normal text-muted-foreground">{s.unit}</span></p></div>)}{(services||[]).length===0&&<p className="text-sm text-muted-foreground">Crea tu primer servicio para comenzar a recibir reservas.</p>}</CardContent></Card></div></div>
}
function Kpi({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <Card><CardContent className="p-4"><div className="flex items-center justify-between text-muted-foreground"><span className="text-xs">{label}</span><Icon className="size-4"/></div><p className="mt-2 text-2xl font-extrabold">{value}</p></CardContent></Card>}
