'use client'
import * as React from 'react'
import { LoaderCircle, Plus, Power, Trash2 } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { formatCLP } from '@/lib/format'

export default function ProviderServicesPage(){const supabase=React.useMemo(()=>createClient(),[]);const [providerId,setProviderId]=React.useState('');const [services,setServices]=React.useState<any[]>([]);const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');const [f,setF]=React.useState({name:'',description:'',price:50000,unit:'por evento'})
const load=React.useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('service_providers').select('id').eq('owner_id',user.id).maybeSingle();if(!p)return;setProviderId(p.id);const {data}=await supabase.from('provider_services').select('*').eq('provider_id',p.id).order('created_at',{ascending:false});setServices(data||[])},[supabase]);React.useEffect(()=>{load()},[load]);async function add(e:React.FormEvent){e.preventDefault();if(!providerId)return;setBusy(true);setError('');const {error}=await supabase.from('provider_services').insert({provider_id:providerId,external_key:`custom-${Date.now()}`,name:f.name,description:f.description,price:Number(f.price),unit:f.unit});if(error)setError(error.message);else{setF({name:'',description:'',price:50000,unit:'por evento'});await load()}setBusy(false)}async function toggle(s:any){await supabase.from('provider_services').update({active:!s.active}).eq('id',s.id);await load()}async function remove(id:string){if(!confirm('¿Eliminar este servicio?'))return;await supabase.from('provider_services').delete().eq('id',id);await load()}
return <div className="mx-auto max-w-5xl px-4 py-10"><p className="text-sm font-semibold text-primary">Prestador</p><h1 className="mt-1 text-3xl font-extrabold">Mis servicios</h1><div className="mt-8 grid gap-6 lg:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Nuevo servicio</CardTitle></CardHeader><CardContent><form onSubmit={add} className="space-y-4"><label className="grid gap-1.5 text-sm">Nombre<Input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label className="grid gap-1.5 text-sm">Descripción<Textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-1.5 text-sm">Precio<Input type="number" min={0} value={f.price} onChange={e=>setF({...f,price:Number(e.target.value)})}/></label><label className="grid gap-1.5 text-sm">Cobro<select className="h-9 rounded-lg border bg-background px-3" value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}><option>por evento</option><option>por persona</option><option>por hora</option></select></label></div>{error&&<p className="text-sm text-destructive">{error}</p>}<Button type="submit" className="w-full" disabled={busy}>{busy?<LoaderCircle className="animate-spin"/>:<Plus/>}Agregar servicio</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Servicios publicados</CardTitle></CardHeader><CardContent className="space-y-3">{services.map(s=><div key={s.id} className="flex items-center justify-between gap-4 rounded-xl border p-4"><div><div className="flex items-center gap-2"><b>{s.name}</b><span className={`rounded-full px-2 py-0.5 text-[10px] ${s.active?'bg-primary/10 text-primary':'bg-muted text-muted-foreground'}`}>{s.active?'Activo':'Pausado'}</span></div><p className="mt-1 text-sm text-muted-foreground">{s.description}</p><p className="mt-2 font-semibold">{formatCLP(s.price)} <span className="text-xs font-normal text-muted-foreground">{s.unit}</span></p></div><div className="flex gap-1"><Button size="icon" variant="outline" onClick={()=>toggle(s)}><Power/></Button><Button size="icon" variant="destructive" onClick={()=>remove(s.id)}><Trash2/></Button></div></div>)}{services.length===0&&<p className="py-12 text-center text-sm text-muted-foreground">Aún no tienes servicios.</p>}</CardContent></Card></div></div>}
